import type { LlmModelDefinition } from 'cs/workbench/services/llm/types';

const openaiDefaults = {
  provider: 'openai',
  apiStyle: 'openai',
  enabled: true,
  supported_service_tiers: ['auto', 'default', 'priority', 'flex'],
  default_service_tier: 'auto',
} as const;

const openai: ReadonlyArray<LlmModelDefinition> = [
  {
    ...openaiDefaults,
    id: 'gpt-5.4-mini',
    label: 'GPT-5.4 Mini',
    snapshots: ['gpt-5.4-mini-2026-03-17'],
    description: 'Openai\'s strongest mini model yet for coding, computer use, and subagents',
    release_date: '2026-03-17',
    knowledge_cutoff_date: '2025-08-31',
    supports_image_input: true,
    input_token_limit: 272_000,
    latency_tier: 'fast',
    reasoningEfforts: ['none', 'low', 'medium', 'high', 'xhigh'],
    recommendedTasks: ['chat'],
  },
  {
    ...openaiDefaults,
    id: 'gpt-5.4-nano',
    label: 'GPT-5.4 Nano',
    snapshots: ['gpt-5.4-nano-2026-03-17'],
    description: 'Openai\'s cheapest GPT-5.4-class model for simple high-volume tasks',
    release_date: '2026-03-17',
    knowledge_cutoff_date: '2025-08-31',
    supports_image_input: true,
    input_token_limit: 272_000,
    latency_tier: 'fast',
    reasoningEfforts: ['none', 'low', 'medium', 'high'],
    recommendedTasks: ['chat'],
  },
  {
    ...openaiDefaults,
    id: 'gpt-5.4',
    label: 'GPT-5.4',
    snapshots: ['gpt-5.4-2026-03-05'],
    description: 'Best intelligence at scale for agentic, coding, and professional workflows.',
    release_date: '2026-03-05',
    knowledge_cutoff_date: '2025-08-31',
    supports_image_input: true,
    default_input_token_limit: 272_000,
    input_token_limit: 922_000,
    reasoningEfforts: ['none', 'low', 'medium', 'high', 'xhigh'],
    recommendedTasks: ['chat', 'reasoning'],
  },
  {
    ...openaiDefaults,
    id: 'gpt-5.3-codex',
    label: 'GPT-5.3 Codex',
    snapshots: ['gpt-5.3-codex-2026-02-05'],
    description: 'Newer Codex-tuned model for coding-heavy chat and reasoning tasks.',
    release_date: '2026-02-05',
    knowledge_cutoff_date: '2025-05-31',
    supports_image_input: true,
    input_token_limit: 272_000,
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    recommendedTasks: ['chat', 'reasoning'],
  },
  {
    ...openaiDefaults,
    id: 'gpt-5.2-codex',
    label: 'GPT-5.2-Codex',
    snapshots: ['gpt-5.2-codex-2025-12-18'],
    description: 'Coding-oriented GPT-5.2 variant for chat and structured reasoning workflows.',
    release_date: '2025-12-18',
    knowledge_cutoff_date: '2025-06-30',
    supports_image_input: true,
    context_window_tokens: 400_000,
    input_token_limit: 272_000,
    max_output_tokens: 128_000,
    reasoningEfforts: ['low', 'medium', 'high', 'xhigh'],
    recommendedTasks: ['chat', 'reasoning'],
  },
  {
    ...openaiDefaults,
    id: 'gpt-5.2',
    label: 'GPT-5.2',
    snapshots: ['gpt-5.2-2025-12-11'],
    description: 'Balanced flagship model for general chat, multimodal tasks, and deeper reasoning.',
    release_date: '2025-12-11',
    knowledge_cutoff_date: '2025-06-30',
    supports_image_input: true,
    context_window_tokens: 400_000,
    input_token_limit: 272_000,
    max_output_tokens: 128_000,
    reasoningEfforts: ['none', 'low', 'medium', 'high', 'xhigh'],
    recommendedTasks: ['chat', 'reasoning'],
  },
  {
    ...openaiDefaults,
    id: 'gpt-5.2-pro',
    label: 'GPT-5.2 Pro',
    snapshots: ['gpt-5.2-pro-2025-12-11'],
    description: 'Higher-effort GPT-5.2 variant optimized for harder reasoning tasks.',
    release_date: '2025-12-11',
    knowledge_cutoff_date: '2025-06-30',
    supports_image_input: true,
    context_window_tokens: 400_000,
    input_token_limit: 272_000,
    max_output_tokens: 128_000,
    reasoningEfforts: ['medium', 'high', 'xhigh'],
    recommendedTasks: ['reasoning'],
  },
  {
    ...openaiDefaults,
    id: 'gpt-4.1',
    label: 'GPT-4.1',
    snapshots: ['gpt-4.1-2025-04-14'],
    description: 'General-purpose multimodal model for standard chat tasks.',
    release_date: '2025-04-14',
    knowledge_cutoff_date: '2024-06-01',
    supports_image_input: true,
    context_window_tokens: 1_047_576,
    default_input_token_limit: 272_000,
    input_token_limit: 1_014_808,
    max_output_tokens: 32_768,
    recommendedTasks: ['chat'],
  },
];

export default openai;
