/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Comet. All rights reserved.
 *  Licensed under the MIT License. See LICENSE.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// AUTOGENERATED - do not edit.
// Regenerate with `npm run codex:gen-protocol`.

export const CODEX_GENERATED_PROTOCOL_SDK_VERSION = '0.142.0';
export const CODEX_GENERATED_PROTOCOL_SOURCE_DIGEST = 'sha256:68bc69eeb6c679c4a8538fcbafe558642d097c30c5359e596d9198b3604d864b';
export const CODEX_GENERATED_PROTOCOL_FILE_COUNT = 654;
