import {
  lxAccount,
  lxAdd,
  lxAddSmall,
  lxAgent,
  lxAgentFilled,
  lxAlignCenter,
  lxAlignJustified,
  lxAlignLeft,
  lxAlignRight,
  lxAnalysis,
  lxAppearance,
  lxArchive,
  lxArrowDown,
  lxArrowLeft,
  lxArrowRight,
  lxArrowUp,
  lxBell,
  lxBellDot,
  lxBellSlash,
  lxBook,
  lxBrowserExplore,
  lxBrowserWeb,
  lxCalendar,
  lxChat,
  lxChatFilled,
  lxCheck,
  lxChevronDown,
  lxChevronLeft,
  lxChevronRight,
  lxChevronUp,
  lxClose,
  lxCode,
  lxCommand,
  lxCopy,
  lxCursor,
  lxCustomize,
  lxCustomizeFilled,
  lxDatabase,
  lxDatabaseFlat,
  lxDiagnostics,
  lxDocx,
  lxDocxBlue,
  lxDownload,
  lxDownloadBox,
  lxDownloadTray,
  lxEdit,
  lxEnter,
  lxEraser,
  lxExport,
  lxExportTray,
  lxEye,
  lxEyeFilled,
  lxFileText,
  lxFiles,
  lxFilter,
  lxFold,
  lxGear,
  lxGitCommit,
  lxH2,
  lxH3,
  lxH4,
  lxH5,
  lxImage,
  lxImageFilled,
  lxInfo,
  lxItalics,
  lxLayoutPanel,
  lxLayoutPanelOff,
  lxLayoutSidebarLeft,
  lxLayoutSidebarLeftOff,
  lxLayoutSidebarRight,
  lxLayoutSidebarRightOff,
  lxLibrary,
  lxLightning,
  lxLinkExternal,
  lxListUnordered,
  lxMenu,
  lxModel,
  lxModelFilled,
  lxOpenai,
  lxOrigin,
  lxParameters,
  lxPass,
  lxPdf,
  lxPdfRed,
  lxPinned,
  lxPreview,
  lxProjects,
  lxProjectsFilled,
  lxQuote,
  lxQuotes,
  lxRefresh,
  lxRemove,
  lxRemoveSmall,
  lxRss,
  lxSave,
  lxScreenFull,
  lxSearch,
  lxSettings,
  lxSplitHorizontal,
  lxSplitPage,
  lxSplitVertical,
  lxStar,
  lxStarFilled,
  lxSummary,
  lxSync,
  lxTranslate,
  lxTrash,
  lxTxtLetter,
  lxUnderline,
  lxUnfold,
  lxUnpin,
  lxWarning,
  lxWrite,
  lxZoomIn,
  lxZoomOut,
  renderIcon,
} from '@chogng/lxicons';

import 'cs/base/browser/ui/lxicons/lxicons.css';

type LxIconFactory = () => string;

const SVG_BY_NAME = {
  'account': lxAccount,
  'add': lxAdd,
  'add-1': lxAddSmall,
  'add-file': lxFileText,
  'add-folder': lxProjects,
  'agent': lxAgent,
  'agent-filled': lxAgentFilled,
  'align-center': lxAlignCenter,
  'align-justified': lxAlignJustified,
  'align-left': lxAlignLeft,
  'align-right': lxAlignRight,
  'anthropic': lxModel,
  'appearance': lxAppearance,
  'archive': lxArchive,
  'arrow-circle-down': lxArrowDown,
  'arrow-circle-left': lxArrowLeft,
  'arrow-circle-right': lxArrowRight,
  'arrow-circle-up': lxArrowUp,
  'arrow-down': lxArrowDown,
  'arrow-left': lxArrowLeft,
  'arrow-right': lxArrowRight,
  'arrow-up': lxArrowUp,
  'batch-download': lxDownloadTray,
  'bell': lxBell,
  'bell-dot': lxBellDot,
  'bell-slash': lxBellSlash,
  'bold': lxWrite,
  'book': lxBook,
  'bracket': lxCode,
  'brain': lxAnalysis,
  'browser': lxBrowserWeb,
  'browser-1': lxBrowserExplore,
  'calendar': lxCalendar,
  'chat': lxChat,
  'chat-filled': lxChatFilled,
  'check': lxCheck,
  'checklist': lxCheck,
  'chevron-down': lxChevronDown,
  'chevron-left': lxChevronLeft,
  'chevron-right': lxChevronRight,
  'chevron-up': lxChevronUp,
  'circle-slash': lxClose,
  'claude-color': lxModel,
  'close': lxClose,
  'cloud': lxDatabase,
  'code': lxCode,
  'code-review': lxDiagnostics,
  'command': lxCommand,
  'command-error': lxWarning,
  'command-start': lxCommand,
  'command-success': lxPass,
  'comment': lxChat,
  'copy': lxCopy,
  'corner-bottom-left': lxArrowDown,
  'corner-bottom-right': lxArrowDown,
  'corner-top-left': lxArrowUp,
  'corner-top-right': lxArrowUp,
  'customize': lxCustomize,
  'customize-filled': lxCustomizeFilled,
  'cursor': lxCursor,
  'database': lxDatabase,
  'database-1': lxDatabaseFlat,
  'deepl-color': lxTranslate,
  'deepseek-color': lxModel,
  'diff-added': lxAdd,
  'diff-removed': lxRemove,
  'discard': lxClose,
  'docx': lxDocx,
  'docx-blue': lxDocxBlue,
  'download': lxDownload,
  'download-2': lxDownloadTray,
  'draft': lxWrite,
  'edit': lxEdit,
  'enter': lxEnter,
  'error': lxWarning,
  'erasure': lxEraser,
  'export': lxExport,
  'export-2': lxExportTray,
  'extensions': lxCustomize,
  'fast': lxLightning,
  'favorite': lxStar,
  'favorite-filled': lxStarFilled,
  'file': lxFileText,
  'file-docx': lxDocx,
  'file-pdf': lxPdf,
  'file-text': lxFileText,
  'files': lxFiles,
  'filter': lxFilter,
  'fold': lxFold,
  'folder': lxProjects,
  'folder-open': lxProjectsFilled,
  'folders': lxProjects,
  'follow': lxPinned,
  'gear': lxGear,
  'gemini-color': lxModel,
  'git': lxGitCommit,
  'git-branch': lxGitCommit,
  'git-commit': lxGitCommit,
  'git-pull-request': lxGitCommit,
  'Github': lxCode,
  'Github-alt': lxCode,
  'Github-inverted': lxCode,
  'glmv-color': lxModel,
  'h1': lxH2,
  'h2': lxH2,
  'h3': lxH3,
  'h4': lxH4,
  'h5': lxH5,
  'hidden': lxEyeFilled,
  'history': lxSummary,
  'html': lxCode,
  'image': lxImage,
  'image-filled': lxImageFilled,
  'info': lxInfo,
  'italics': lxItalics,
  'javascript': lxCode,
  'js': lxCode,
  'keyboard-tab': lxEnter,
  'kimi': lxModel,
  'kimi-color': lxModel,
  'lattice-dark': lxModel,
  'layout': lxLayoutPanel,
  'layout-panel': lxLayoutPanel,
  'layout-panel-off': lxLayoutPanelOff,
  'layout-sidebar-left': lxLayoutSidebarLeft,
  'layout-sidebar-left-off': lxLayoutSidebarLeftOff,
  'layout-sidebar-right': lxLayoutSidebarRight,
  'layout-sidebar-right-off': lxLayoutSidebarRightOff,
  'letter-t': lxTxtLetter,
  'library': lxLibrary,
  'link-external': lxLinkExternal,
  'list-fold': lxFold,
  'list-ordered': lxListUnordered,
  'list-unfold': lxUnfold,
  'list-unordered': lxListUnordered,
  'local': lxDatabase,
  'lock': lxPass,
  'markdown': lxFileText,
  'md': lxFileText,
  'mention': lxParameters,
  'message-more': lxChat,
  'mic': lxCommand,
  'mic-filled': lxCommand,
  'minimax-color': lxModel,
  'model': lxModel,
  'model-filled': lxModelFilled,
  'more': lxMenu,
  'more-2': lxMenu,
  'note': lxFileText,
  'ollama': lxModel,
  'openai': lxOpenai,
  'origin': lxOrigin,
  'pause': lxClose,
  'pdf': lxPdf,
  'pdf-red': lxPdfRed,
  'pinned': lxPinned,
  'preview': lxPreview,
  'preview-off': lxEyeFilled,
  'projects': lxProjects,
  'projects-filled': lxProjectsFilled,
  'question': lxInfo,
  'quote': lxQuote,
  'quotes': lxQuotes,
  'reasoning': lxAnalysis,
  'refresh': lxRefresh,
  'remove': lxRemove,
  'remove-1': lxRemoveSmall,
  'repo-fetch': lxDownloadBox,
  'repo-pull': lxDownload,
  'repo-push': lxExport,
  'rss': lxRss,
  'sandbox': lxDiagnostics,
  'save': lxSave,
  'screen-full': lxScreenFull,
  'search': lxSearch,
  'select': lxCursor,
  'select-all': lxCheck,
  'settings': lxSettings,
  'show': lxEye,
  'spilt-page': lxSplitPage,
  'split-horizontal': lxSplitHorizontal,
  'split-vertical': lxSplitVertical,
  'start': lxCommand,
  'stop-circle': lxClose,
  'symbol-numeric': lxParameters,
  'sync': lxSync,
  'tasklist': lxCheck,
  'terminal': lxCommand,
  'terminal-cmd': lxCommand,
  'terminal-git-bash': lxCommand,
  'text': lxTxtLetter,
  'text-size': lxParameters,
  'three-bars': lxMenu,
  'translate': lxTranslate,
  'trash': lxTrash,
  'ts': lxCode,
  'tx': lxTxtLetter,
  'typescript': lxCode,
  'underline': lxUnderline,
  'unfold': lxUnfold,
  'unlimited': lxLightning,
  'unsave': lxUnpin,
  'voice-circle': lxCommand,
  'voice-circle-filled': lxCommand,
  'warning': lxWarning,
  'write': lxWrite,
  'zhipu-color': lxModel,
  'zoom-in': lxZoomIn,
  'zoom-out': lxZoomOut,
} as const satisfies Record<string, LxIconFactory>;

export type LxIconName = keyof typeof SVG_BY_NAME;

export function createLxIcon(name: LxIconName, className = '') {
  const icon = document.createElement('span');
  icon.className = ['comet-lx-icon', `comet-lx-icon-${name}`, className].filter(Boolean).join(' ');
  icon.setAttribute('aria-hidden', 'true');
  renderIcon(SVG_BY_NAME[name], icon);
  return icon;
}

export function createLxLoadingIcon(className = '') {
  return createLxIcon(
    'sync',
    ['comet-lx-icon-loading', 'comet-lx-icon-modifier-spin', className].filter(Boolean).join(' '),
  );
}
